#!/usr/bin/perl
# vim: ts=2 sw=2 ft=perl
eval 'exec perl -x -wS $0 ${1+"$@"}'
  if 0;
$|++;
use common::sense;
use autodie;
use Nobody::Util;
our(@VERSION) = qw( 0 1 0 );
use Digest::MD5 qw(md5_hex);
use Path::Tiny;
sub process($$){
  @_;   
};
for(@ARGV){
  my ($md5) = process(path($_),"$_");
  ddx( { $_ => $md5 } )
}
